name: sistem_kel3
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.5.0
  http: ^0.13.6
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - videos/
    - images/

  # Jika mau tambahkan fonts, bisa di sini
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

  # Jika mau pakai flutter_lints bisa dipindah ke dev_dependencies
  # flutter_lints: ^5.0.0
